export const SEARCH_FOCUS = 'header/SEARCH_FOCUS'
export const GET_LIST = 'header/GET_LIST'
export const MOUSE_ENTER = 'header/MOUSE_ENTER'
export const MOUSE_LEAVE = 'header/MOUSE_LEAVE'
export const PAGE_CHANGE = 'header/PAGE_CHANGE'
